config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  resources :products, only: [:index,:new, :edit, :show, :create,:destroy, :update] do
  end

  resources :users, only: [:index,:new, :edit, :show, :update, :delete] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImagesUploader
  belongs_to :user

  validates :title,:describe, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with :name => ENV['BASIC_AUTH_USERNAME'], :password => ENV['BASIC_AUTH_PASSWORD'] if Rails.env == "production"
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :first_name_jp, :last_name_jp, :add_ress])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @user = current_user
    @producta = Product.all.order("id desc").limit(9)
  end

  def new
    @products = Product.new
  end


  def show
    @product = Product.find(params[:id])
  end

  def create
    @product  = Product.create(title: product_params[:title], describe: product_params[:describe], image: product_params[:image], user_id: current_user.id)
    redirect_to products_path
  end

  def destroy
    products = Product.find(params[:id])
    if products.destroy
       redirect_to users_path
    else
      render :show
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :describe, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to :action => "index" unless user_signed_in?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.new
    @user = current_user
    @product = Product.where(user_id: current_user.id)
  end

  def show
    @product = Product.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaceGood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PlaceGood
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js", :type => "text/javascript"}
    %script{:src => "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"}s
  %body
    = yield

app/views/products/index.html.haml
.products-top
  =render "shared/header"
  .errorTextTitle タイトルが入力されてません。
  .errorTextDescribe 説明が入力されてません。
  .products-top--content
    -@producta.each do |products|
      .products-top--content--each
        = link_to product_path(products.id), class: "link-top-left" do
          //画像表示
          -# .products-top--image--left--objects
          -#   = image_tag products.image.to_s
          .top--content--title
            = products.title
          .top-image-left--describe
            = products.describe
.product-vote
  .product-vote--title 投稿
  .product-vote--main
    = form_for :product, url: products_path do |f|
      -# .vote-table--title--text タイトル
      -# = f.text_field :title, class: "vote-form--title-field",placeholder: "タイトル"
      .cp_iptxt
        = f.text_field :title, class: "ef",placeholder: "",type: "text"
        -# %input.ef{:placeholder => "", :type => "text"}/
        %label タイトル
        %span.focus_line
          %i
      .cp_iptxt
        = f.text_field :describe, class: "efw",placeholder: "",type: "text"
        -# %input.ef{:placeholder => "", :type => "text"}/
        %label 説明
        %span.focus_line
          %i
        -# .vote-table--describe--text 説明
        -# = f.text_field :describe, class: "vote-form--describe-field",placeholder: "説明"
      .vote-table--image--image 画像
      = f.file_field :image, class: "vote-form--image-field"
      .vote-btn-parent
        .product-vote--next
          = button_tag "投稿",class: "vote-btn"
.scrollTop
  %i.fas.fa-chevron-up.fa-2x
.scrollDown
  %i.fas.fa-chevron-down.fa-2x

app/views/products/new.html.haml
.product-vote
  .product-vote--title 投稿
  .product-vote--main
    = form_for :product, url: products_path do |f|
      %table.vote-table
        %td.vote-table--title
          .vote-table--title--text タイトル
          = f.text_field :title, class: "vote-form--title-field"
        %td.vote-table--describe
          .vote-table--describe--text 説明
          = f.text_field :describe, class: "vote-form--describe-field"
        %td.vote-table--image
          .vote-table--image--image 画像
          = f.file_field :image, class: "vote-form--image-field"
      .product-vote--next
        = button_tag "投稿",class: "vote-btn"

app/views/products/show.html.haml
.user-top--btn
  = link_to "TopPage", products_path, class: "user-top--btn-link"
.scrollTop
  %i.fas.fa-chevron-up.fa-2x
.scrollDown
  %i.fas.fa-chevron-down.fa-2x

- if current_user.id == @product.user_id
  = link_to "editBtn", "#", class: "editBtn"
  = link_to "Mypage", users_path, class: "MypageLink"
-else

%table.productDetails
  %tr.productDetailsTitle
    = @product.title
  %tr.productDetailsImage
    =image_tag @product.image.to_s,class: "imageObject"
  %tr.productDetailsDescribe
    =@product.describe

app/views/shared/_header.html.haml
.products-top--title
  = link_to products_path do
    .products-top--title--text
      .products-top--title--text-g タイトル
  %table.products-top--title--right
    %tr.table-record
      //ログイン後　マイページで無ければ表示、マイページはトップページへのリンク
      - if user_signed_in?
        -unless current_page?(users_path)
        -else
          %td.products-top--title--right--delete
            =link_to "アカウントを削除する", users_path, method: :delete, class: "delete-link"
      - if user_signed_in?
        -unless current_page?(users_path)
          %td.products-top--title--right--vote
            %i.far.fa-comment-alt
            = link_to "投稿", new_product_path ,class: "vote-link"
        -else
          %td.products-top--title--right--vote
            %i.far.fa-comment-alt
            = link_to "top", products_path ,class: "vote-link"
        %td.products-top--title--right--mypage
          %i.far.fa-address-card
          = link_to users_path,class: "mypage-link" do
            =@user.nickname
        %td.products-top--title--right--logout
          %i.fas.fa-door-open
          = link_to "ログアウト", destroy_user_session_path,method: :delete, class: "logout-link"
      -else
        %td.products-top--title--right--login
          %i.fas.fa-pen-fancy
          = link_to "ログイン", new_user_session_path ,class: "login-link"
          .title--right--login--underbar
        %td.products-top--title--right--table
          %i.fas.fa-user-tie
          = link_to "新規登録", new_user_registration_path, class: "title--table-link"

app/views/users/index.html.haml
=render "shared/header"
.user-top
  .user-top--title 登録情報
  %table.user-top--main
    %tr.user-top--main--nickname
      %th.user-top--main--nickname--left
        .user-top--main--nickname--left--text ニックネーム
      %td.user-top--main--nickname--right
        = @user.nickname
    %tr.user-top--main--fist-name
      %th.user-top--main--fist-name--left
        .user-top--main--fist-name--left--text 苗字
      %td.user-top--main--fist-name--right
        = @user.first_name
    %tr.user-top--main--last-name
      %th.user-top--main--last-name--left
        .user-top--main--last-name--left--text 名前
      %td.user-top--main--last-name--right
        = @user.last_name
    %tr.user-top--main--fist-name-jp
      %th.user-top--main--fist-name-jp--left
        .user-top--main--fist-name-jp--left--text 苗字(フリガナ)
      %td.user-top--main--fist-name-jp--right
        = @user.first_name_jp
    %tr.user-top--main--last-name-jp
      %th.user-top--main--last-name-jp--left
        .user-top--main--last-name-jp--left--text 名前(フリガナ)
      %td.user-top--main--last-name-jp--right
        = @user.last_name_jp
    %tr.user-top--main--address
      %th.user-top--main--address--left
        .user-top--main--address--left--text 住所
      %td.user-top--main--address--right
        = @user.add_ress
  %table.user-vote
    %tbody.user-vote--body
      .user-vote--title 投稿一覧
      %tr.user-vote--body--record
        %td.user-vote--body--record--cell ID
        %td.user-vote--body--record--cell タイトル
        %td.user-vote--body--record--cell 投稿日
        %td.user-vote--body--record--cell 投稿内容
        %td.user-vote--body--record--cell
      -@product.each do |products|
        %tr.user-vote--body--record
          %td.user-vote--body--record--cell
            = products.id
          %td.user-vote--body--record--cell
            = products.title
          %td.user-vote--body--record--cell
            = products.created_at.strftime("%Y年%m月%d日%H:%M")
          -# each内での画像表示
          %td.user-vote--body--record--cell
            = link_to product_path(products.id) do
              .products--describe--link
                = products.describe
          %td.user-vote--body--record--cell
            = link_to "削除", product_path(products.id), method: :delete

.scrollTop
  %i.fas.fa-chevron-up.fa-2x
.scrollDown
  %i.fas.fa-chevron-down.fa-2x